feat: 소셜로그인/회원가입 기능 구현
ConceptBe/conceptbe-backend pull request #5
Opened 2023-12-28 03:01 UTC by parkmuhyeun

## 📄 Summary
- #3 

소셜로그인/회원가입 플로우를 살펴보면 다음과 같습니다.

1. 프론트에서 소셜로그인 버튼 -> /oauth/{oauthServerType}으로 요청하게 되면 authCode와 함께 redirectUrl로 리다이렉트됩니다.
2. 프론트에서 해당 authCode의 유저가 회원인지 확인합니다.
3. 확인 후 회원이면 로그인
4. 회원이 아니면 회원가입 하는 페이지로 이동 후 추가정보를 받고 회원가입을 하게 됩니다.

API 명세 관련해서는 노션 참고해주세요.

현재 코드가 많기 때문에 여기서 한번 끊고 추가적으로 PR 보내려고 합니다.

### 앞으로 추가적으로 하려고 하는 것들
- 인가 확인 절차 추가 + Argument resolver 
- Member 패키지 고칠 예정
- jwt 탈취 관련 생각
- Transactional 범위 분리 예정
- 2차때 naver 추가 예정
- Refresh token 추가 예정
- Validation 추가 필요
- 스킬관련 저장로직 추가해야됨
- 소셜로그인 테스트는 어차피 다 모킹 테스트가 될거 같아 고민 중

## 🙋🏻 More
> 코드 관련해서 자유롭게 의견 남겨주세요!

2023-12-28 20:07 UTC, kpeel5839 requested changes
모밀!

너무 고생하셨어요!

쉽지 않은 기능임에도 불구하고 멋지게 해주셨군요

확장성을 고려한 구조도 아주 멋져요!

코멘트 이외에 궁금한 사항 여쭤보고 물러나도록 하겠습니다.

---

현재 application.yml 에 datasource 가 MySQL 로 설정되어 있어 Docker-Compose 를 정의해놓으신 것 같은데, 일단 local 로 개발할 때에는 h2 를 사용하시는 건 어떤가요?

```yml
spring:
  datasource: 
    username: sa
    url: jdbc:h2:mem:conceptBe;MODE=MySQL
  h2:
    console:
      enabled: true
      path: /h2-console
	  ... 이어서
```

---

너무 고생하셨습니다 모밀!

코드가 너무 좋아서 따로 말씀드릴 사항이 많지 않네요!

댓글들에 대한 답변 혹은 반영을 해주신다면 Approve 해드리도록 하겠습니다!

2023-12-28 20:07 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/application/OauthService.java
> +    //TODO 외부와 Transactional 분리 예정
파사드 패턴으로 분리하시는건가요 홍홍홍

2023-12-28 20:07 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/application/OauthService.java
> +        OauthMemberInformation oauthMemberInformation = oauthMemberClientHandler.getOauthMemberInformation(oauthServerType, code);
줄이 너무 길어서 경계선을 넘어갔어요!

2023-12-28 20:07 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/infra/oauth/kakao/client/KakaoMemberClient.java
> +        KakaoAccount kakaoAccount = kakaoMemberResponse.kakaoAccount();
결국 이렇게 두 번 요청했군용 홍홍

2023-12-28 20:07 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/config/JwtCredentials.java
> +
```txt
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'jwt' to kr.co.conceptbe.auth.config.JwtCredentials:

Reason: java.lang.IllegalStateException: Unable to create instance for kr.co.conceptbe.auth.config.JwtCredentials

Action:

Update your application's configuration
Property: jwt.access-token-expiration-time
Value: "604800000"
Origin: class path resource [application.yml] - 29:30
Reason: java.lang.IllegalStateException: No setter found for property: access-token-expiration-time

```

현재 위와 같은 에러가 뜨네요!

해당 클래스를 record 로 바꾸거나, 혹은 final 과 Setter 를 붙여주면 위 문제가 해결되더라고요!

하지만, 후자의 방법보다는 record 로 바꾸는게 나아보여요! 모밀 생각은 어떠세요??

2023-12-28 20:07 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/presentation/OauthController.java
> +
진짜 이상하네요...

```java
@PathVariable("oauthServerType") OauthServerType oauthServerType
```

인자를 저렇게 해주지 않으면 Converter 가 동작을 안해요... 왜 그러죠?? 이유를 아시나요?

모밀은 해당 API 가 잘 동작했나요?

2023-12-28 20:07 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/common/exception/GlobalExceptionHandler.java
> +}
해당 메서드는 저희가 정의한 Exception 이외의 Exception 인 경우 실행되는 것인가요?

2023-12-28 20:07 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/common/exception/ConceptBeException.java
> +}
추상화가 과하지 않고 좋아요 굳굳!

2023-12-28 20:07 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/infra/oauth/kakao/authcode/KakaoAuthCodeRequestUrlProvider.java
> +public class KakaoAuthCodeRequestUrlProvider implements AuthCodeRequestUrlProvider {
확장에 유연한 구조 굳굳!

2023-12-28 20:07 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/presentation/dto/TokenResponse.java
> +}
해당 클래스의 정팩메는 일관성을 유지해주기 위함인가요??

2023-12-29 01:03 UTC, parkmuhyeun commented
> 현재 application.yml 에 datasource 가 MySQL 로 설정되어 있어 Docker-Compose 를 정의해놓으신 것 같은데, 일단 local 로 개발할 때에는 h2 를 사용하시는 건 어떤가요?

좋읍니다~!

2023-12-29 01:04 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/auth/application/OauthService.java
> +    //TODO 외부와 Transactional 분리 예정
맞아용

2023-12-29 01:05 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/auth/application/OauthService.java
> +        OauthMemberInformation oauthMemberInformation = oauthMemberClientHandler.getOauthMemberInformation(oauthServerType, code);
ㅋㅋㅋㅋ 아 줄 애매한 것들은 어떻게 처리할지 좀 고민이네요!!!
막 예쁘게 띄어지지도 않고 적당한 곳에서 개행해야될까여

2023-12-29 01:07 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/auth/infra/oauth/kakao/client/KakaoMemberClient.java
> +        KakaoAccount kakaoAccount = kakaoMemberResponse.kakaoAccount();
마자요 네이버는 OIDC 지원안해서 표준 맞출려고 이렇게 했읍니다!
추후에 리팩터링 할 필요 있으면 하겠슴미다.

2023-12-29 01:11 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/auth/config/JwtCredentials.java
> +
현재 저는 잘 실행이 되고있는데여 보안때문에 application.yml을 다 올리지 않아서 그럴 수도 있을거 같아여 요건 개인적으로 yml 보내드리겠습니다!

2023-12-29 01:16 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/auth/presentation/OauthController.java
> +
넹 "/oauth/kakao" 이렇게 요청하신거 맞나요!?

2023-12-29 01:19 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/common/exception/GlobalExceptionHandler.java
> +}
요건 valid 유효성 검사했을 떄 처리해주는 exceptionhandler입니닷!

2023-12-29 01:22 UTC, dnd2dnd reviewed
확인했습니다.

2023-12-29 01:22 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/common/exception/GlobalExceptionHandler.java
> +}
ConceptBeException와 유효성 체크 에러를 잡아주는 것 같아요

2023-12-29 01:25 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/auth/presentation/dto/TokenResponse.java
> +}
전에 쓰던 습관이 있어서 자연스럽게 나온거 같아용,, ㅋㅋㅋ  다른 DTO는 생성자를 통해 만들어줬기 때문에 통일성을 주기 위해 삭제하겠씁니다!

2023-12-29 01:48 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/presentation/OauthController.java
> +
당근이져어어어엉 저희 서비스에 요청해보니까 코드는 똑같은데 잘 동작하더라고요

2023-12-29 01:49 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/common/exception/GlobalExceptionHandler.java
> +}
예상치 못한 exception을 잡아내는 핸들러도 필요하겠군요!!

2023-12-29 01:56 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/common/exception/GlobalExceptionHandler.java
> +}
꼼꼼 매뜌 머야 👍🏻

추가했습니닷

2023-12-29 08:17 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/application/OauthService.java
> +        OauthMemberInformation oauthMemberInformation = oauthMemberClientHandler.getOauthMemberInformation(oauthServerType, code);
개행이 좋아보여요 쟈기

2023-12-29 08:17 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/infra/oauth/kakao/client/KakaoMemberClient.java
> +        KakaoAccount kakaoAccount = kakaoMemberResponse.kakaoAccount();
알러뷰

2023-12-29 08:19 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/presentation/dto/TokenResponse.java
> +}
저도 일관성을 유지만 해준다면 무엇이든 괜찮아보여요!

2023-12-29 16:04 UTC, kpeel5839 approved these changes
변경사항 확인했어요 모밀~!

고생하셨습니다 ❤️

2023-12-29 16:04 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/common/exception/GlobalExceptionHandler.java
> +                String.format("서버에서 알 수 없는 오류가 발생했습니다 : %s", exception.getMessage())));
String.format 굳굳!

2023-12-29 16:05 UTC, merged