feat: 게시글 상세 조회 & 댓글 작성 추가
ConceptBe/conceptbe-backend pull request #7
Opened 2023-12-30 00:12 UTC by dnd2dnd

## 📄 Summary
> 게시글 상세 조회

댓글 API 추가

## 🙋🏻 More
>

2023-12-31 13:12 UTC, parkmuhyeun reviewed
역시 상세페이지라 보내는 데이터가 엄청나게 많군여
고생하셨습니다 선웅님~

일단 이번에는 구체적인 것보다 전체적으로 한번 코멘트 남겨봤씁니다!

2023-12-31 13:12 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/controller/CommentController.java
> +@RequestMapping("/api/v1/comment")
웹서비스할 때 기존 버전도 호환되게 하면서 신규 버전을 배포해본적이 없어서 궁금한데

웹서비스도 버저닝을 하는게 좋은지 궁금합니닷

+아 그리고 복수형인 comments는 어떠신가여

2023-12-31 13:12 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/controller/CommentController.java
> +	@PostMapping("")
("") 은 없어도 좋을 것 같아요!

2023-12-31 13:12 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/controller/CommentController.java
> +			@PathVariable(name = "comment_id") Long commentId) {
개행부분이 4칸보다 더 많이 되어있는 것 같슴니닷

2023-12-31 13:12 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/dto/CommentCreateRequest.java
> +public class CommentCreateRequest {
혹시 record 써보시는건 어떤가요!?

2023-12-31 13:12 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/dto/CommentResponse.java
> +
여기 공백 한 줄이 더 들어간 거 같아요!

2023-12-31 13:12 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +	public ResponseEntity<ListResponse<CommentResponse>> getChildCommentList(Long commentId) {
service위에 transactional 붙이고 여기에만 readOnly 붙이는 건 어떤가욧

2023-12-31 13:12 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +			.orElseThrow(() -> new IllegalArgumentException("Not Found ID : " + commentId));
repository에 다음과 같이 쓰면 중복코드들 제거할 수 있을거 같은데 어떠신가용

```java
default Comment getById(Long commentId) {
        return findById(commentId).orElseThrow(
            () -> new IllegalArgumentException("Not Found ID : " + commentId));
}
```

2023-12-31 13:12 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +	public ResponseEntity<CommonResponse> createComment(CommentCreateRequest commentCreateRequest) {
완전 빡세게는 아니더라도 서비스 전체적으로 가독성 증가를 위해 최소한의 분리를 하면 좀 더 잘 읽힐 것 같아요!

2023-12-31 13:12 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		return toListResponse("댓글 조회 성공", HttpStatus.OK.value(), commentResponseList);
[ResponseEntity](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/ResponseEntity.html)는 service보다 Controller나 외부 API를 주고받는 곳(restTemplate 이용하는 곳)에서 사용하는게 더 어울린다고 생각하는데 어떻게 생각하시나요!?

2023-12-31 13:12 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/dto/CommentResponse.java
> +	private List<String> memberSkillList;
memberSkills로도 충분히 나타낼 수 있을거 같은데 어떤가용

2023-12-31 13:12 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/common/entity/utils/CommonResponse.java
> +public class CommonResponse {
이거 CommonResponse 두고 dto 전체적으로 extends 하는거 백엔드끼리 한번 얘기해보면 좋을거 같아요!!

2024-01-01 13:44 UTC, kpeel5839 requested changes, later dismissed
선웅님 너무 고생하셨습니다!

리뷰를 너무 늦게 남겼네요!

피드백 남겨드린 것에 대해 답변 남겨주시면 감사할 것 같습니다!

2024-01-01 13:44 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/comment/Comment.java
> +        if(this.comments == null) this.comments = new ArrayList<>();
현재 comments 가 null 일 경우는 없지 않을까요?!

그리고 아래와 같이

```java
if (조건문) {
        수식...
}
```

가독성을 위해 중괄호를 쳐주는건 어떨까요??

2024-01-01 13:44 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/comment/Comment.java
> +    @Builder
개인적인 생각으로는 현재 nullable 한 컬럼은 Comment 에 존재하지 않는다고 생각해요! 그래서 Builder 패턴을 사용하기 보다는 생성자를 사용하는 것은 어떻게 생각하시나요?

2024-01-01 13:44 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/idea/dto/IdeaDetailResponse.java
> +public class IdeaDetailResponse {
해당 클래스를 record 로 선언해주는 것은 어떨까요?

아무래도 현재 저희의 Java 버전이 17 이기도 해서 record 의 이점을 최대한 살리는 것이 좋을 것 같아서요!

그러면 아래와 같은 형식으로 바꿔볼 수 있지 않을까요?

```java
public record IdeaDetailResponse {
        String imageUrl,
        String nickname,
        List<String> sk,llList;
        String title,
        String date,
        String introduce,
        List<String> branchList,
        List<String> purposeList,
        String cooperationWay,
        String recruitmentPlace,
        List<String> teamRecruitmentsList,
        Integer likesCount,
        Integer commentsCount,
        Integer bookmarksCount,
        Integer hits,
        List<CommentResponse.CommentParentResponse> commentParentResponseList
}
```

2024-01-01 13:44 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		return toListResponse("댓글 조회 성공", HttpStatus.OK.value(), commentResponseList);
저도 그렇게 생각합니다!

2024-01-01 13:44 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/idea/service/IdeaService.java
> +	public ResponseEntity<CommonResponse.SingleResponse<IdeaDetailResponse>> getDetailIdeaResponse(Long ideaId) {
제가 잘못 본 것일수도 있지만, 해당 메서드에서 Builder 패턴의 단점이 여실히 드러난 것 같아요!

당연하게도 더블체크 하셨겠지만, 현재 List<CommentResponse.CommentParentResponse> list 는 ideaDetailResponse 에 포함되지 않은 것 같아요!

이 부분을 추가해줘야 할 것 같습니다!

2024-01-01 13:44 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/idea/service/IdeaService.java
> +		}
현재 해당 부분이 View 부분과 너무 강한 결합을 맺고 있는 것 같아요.

그렇기 때문에, View 딴의 요구사항이 바뀌더라도 해당 코드는 바뀌어야 할 것 같아요!

추후, 이는 유지보수성을 떨어뜨릴 수도 있을 것 같구요!

그렇기 때문에, 이러한 부분은 화면딴에서 처리할 수 있도록 두는 것은 어떨까요??!

2024-01-01 13:44 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/idea/service/IdeaService.java
> +	}
이 부분도 위에서 단 댓글과 동일한 의견입니다!

2024-01-01 13:44 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		return toCommonResponse("댓글 작성", HttpStatus.OK.value());
댓글 작성이라는 메세지보다는 201 응답코드를 활용하는 것은 어떨까요?

그렇기 때문에 CustomResponse 보다는 ResponseEntity.created(...) 와 같은 메서드를 활용하는 것은 어떨까요 ?

2024-01-01 13:44 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		comment.updateContent("삭제된 댓글입니다.");
삭제된 댓글입니다 너무 좋은 것 같습니다 ! 굳굳

2024-01-01 13:44 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		return toCommonResponse("댓글 삭제", HttpStatus.OK.value());
HttpStatus 를 OK 가 아닌 NO_CONTENT 로 하시는 것은 어떠신가요 ?

2024-01-01 13:44 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		Comment comment = commentRepository.findById(commentId)
주석을 통해서 저희에게 의견을 전달하기 위함이라면 // TODO : ... 이런식으로 작성하는 것도 좋을 것 같아요! 아무래도 찾기 편할테니까요 ㅎㅎ

2024-01-01 13:44 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/common/entity/utils/CommonResponse.java
> +public class CommonResponse {
현재로서 CommonResposne 는 오히려 복잡성을 증가시키는 것 같기도해요 SingleResponse 는 그저 하나의 객체만을 반환하면 되는 것이고, ListResponse 는 List 라는 자료구조를 활용하여 RepsonseEntity<List<...>> 로 반환하면 되는 것이니까요!

2024-01-01 14:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/controller/CommentController.java
> +@RequestMapping("/api/v1/comment")
네 좋습니다

2024-01-01 14:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/controller/CommentController.java
> +	@PostMapping("")
이건 습관..

2024-01-01 14:10 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/dto/CommentResponse.java
> +
수정하겠습니다.

2024-01-02 14:28 UTC, parkmuhyeun requested changes
고치느라 고생하셨습니다!! 👍🏻👍🏻

이번에는 조금 더 자세한 부분과 함게 코멘트 몇 개 더 남겼습니다!

2024-01-02 14:28 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/bookmark/BookmarkID.java
> +public class BookmarkID implements Serializable {
오옹 복합키를 pk로 두셨군여 저도 이 방법은 안 써봤는데 재밌겠네여 👍🏻

+제일 위에 공백 한 줄 빠졌읍니다!

2024-01-02 14:28 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/bookmark/controller/BookmarkController.java
> +		@RequestParam(name = "member_id") Long memberId) {
#8 머지 되면 인증정보가 넘어올거라 다음 PR부터는 @Auth나 @OptionalAuth로 AuthCredentials 받으시면 될 것 같습니다!

2024-01-02 14:28 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/dto/CommentResponse.java
> +	public static CommentResponse of(Comment comment) {
from인 것 같아요!

2024-01-02 14:28 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/controller/CommentController.java
> +		List<CommentResponse> commentResponseList = commentService.getChildCommentList(commentId);
commentResponses 어떠신가용!?

2024-01-02 14:28 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/controller/CommentController.java
> +	public ResponseEntity<List<CommentResponse>> getChildCommentList(
제가 로직은 이제 읽었는데 idea를 읽으면 부모 댓글을 응답주는 걸로 보입니다! 거기서 각 부모 댓글마다 다 api를 요청하는건 건가요??

2024-01-02 14:28 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		}
commentCreateRequest.parentId() != null 이 부분을 처음보면 인지하는데 너무 오래걸려서 method로 빼서 어떤 건지 알려주면 더 가독성이 좋아질 것 같아요(isChildComment 같은)

그리고 부모일 때는 null말고 자기 자신을 넣어서 null을 방지할 수 있을 것 같읍니다!

2024-01-02 14:28 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +			.orElseThrow(() -> new IllegalArgumentException("Not Found ID : " + commentId));
repo에서 만든 getById로 가져올 수 있지 않나요?

2024-01-02 14:28 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/idea/application/IdeaService.java
> +        if(optionalIdeaLike.isPresent()) {
isPresent 보다는 요건 어떠신가여!?

```java
optionalIdeaLike.ifPresentOrElse(
            ideaLike ->  ideaLikesRepository.deleteById(ideaLikeID),
            () -> {
                IdeaLike ideaLike = new IdeaLike(member, idea);
                ideaLikesRepository.save(ideaLike);
                idea.addIdeaLikes(ideaLike);
            }
        );
```

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/Comment.java
> +    @Builder
제일 상위 댓글 기준으로는 부모 댓글이 없으니까
```
Comment parentComment;
```
해당 코드 같은 경우에는 null이 들어갈 수 있지 않을까요

들어가야하는 값이 있다 생각하시면 말씀해주시면 감사하겠습니다

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +	public ResponseEntity<ListResponse<CommentResponse>> getChildCommentList(Long commentId) {
좋습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +			.orElseThrow(() -> new IllegalArgumentException("Not Found ID : " + commentId));
좋은 것 같습니다.

해당 코드들 전부 수정하겠습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		return toListResponse("댓글 조회 성공", HttpStatus.OK.value(), commentResponseList);
수정했습니다.

이것도 제 습관입니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		return toCommonResponse("댓글 작성", HttpStatus.OK.value());
수정했습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		Comment comment = commentRepository.findById(commentId)
네 알겠습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		return toCommonResponse("댓글 삭제", HttpStatus.OK.value());
네 알겠습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/common/entity/utils/CommonResponse.java
> +public class CommonResponse {
네 알겠습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/idea/dto/IdeaDetailResponse.java
> +public class IdeaDetailResponse {
네 알겠습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/Comment.java
> +        if(this.comments == null) this.comments = new ArrayList<>();
네 알겠습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/dto/CommentResponse.java
> +	private List<String> memberSkillList;
반영하겠습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/idea/service/IdeaService.java
> +		}
알겠습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/idea/service/IdeaService.java
> +	public ResponseEntity<CommonResponse.SingleResponse<IdeaDetailResponse>> getDetailIdeaResponse(Long ideaId) {
감사합니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/bookmark/BookmarkID.java
> +public class BookmarkID implements Serializable {
처음엔 그냥 했었는데 주석으로 '복합키로 하면 될 것 같다'라고 되어있어서 했었는데 ㅋㅋ

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/bookmark/controller/BookmarkController.java
> +		@RequestParam(name = "member_id") Long memberId) {
네, 이 부분은 제가 임시입니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/dto/CommentResponse.java
> +	public static CommentResponse of(Comment comment) {
앗 수정하겠습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/controller/CommentController.java
> +		List<CommentResponse> commentResponseList = commentService.getChildCommentList(commentId);
네

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/controller/CommentController.java
> +	public ResponseEntity<List<CommentResponse>> getChildCommentList(
피그마를 확인해보니, 처음 게시글에 들어갔을 때는 부모 댓글만 보이고, 더 보기를 눌렀을 때만 대댓글이 보이는 구조 같더라구요

결론적으로 첫 idea를 읽을 시 -> 부모 댓글 전부 출력 -> 각 부모 댓글마다 API 요청 맞습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		}
parentId는 comment의 id 값(기본 키)이라 자기 자신이 무슨 id인지 모르기 때문에
null 아니면 0을 써야할 것 같은데 이 부분은 일단 저렇게 하고 프론트와 조율 예정이였습니다.

method로는 빼보겠습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +			.orElseThrow(() -> new IllegalArgumentException("Not Found ID : " + commentId));
네 수정하겠습니다.

2024-01-03 05:05 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/idea/application/IdeaService.java
> +        if(optionalIdeaLike.isPresent()) {
네 그렇게 수정하겠습니다.

사실 제가 lambda나 stream를 잘 사용하지 못해서 가독성이 오히려 더 안좋은 것 같아 지양하고 있습니다.
최대한 사용하고 있는데 그렇지 못한 코드가 있으면 알려주시면 수정하겠습니다.

2024-01-03 05:07 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		}
저장하고나서 update를하면 자기 자신도 넣을 수 있습니다!

2024-01-03 05:08 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/controller/CommentController.java
> +	public ResponseEntity<List<CommentResponse>> getChildCommentList(
<img width="337" alt="image" src="https://github.com/ConceptBe/conceptbe-backend/assets/76938931/0c01ee44-44c8-4649-9320-8c6004747b1a">

대댓글도 같이 보이는 구조 아닌가여?

2024-01-03 05:58 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +		}
아 51줄 이야기 하시는 거였군요 알겠습니다

2024-01-04 01:35 UTC, parkmuhyeun requested changes
일단 여기 코멘트까지만 리팩토링하고 프론트랑 맞춰보셔야 될거 같고 추후에 추가 리팩토링하면 더 좋을 것 같습니다!

2024-01-04 01:35 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +			comment.addParentComment(comment);
부모 댓글은 parent가 null이라 48번째 줄은 필요없지 않나요?

2024-01-04 01:35 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/idea/application/IdeaService.java
> +        }
이 부분도 idea 객체 안에 넣으면 좀 더 객체지향적일거 같긴한데 빨리 프론트랑 맞춰보는게 더 중요할거 같아서 이번에는 이렇게하고 다음에 테스트 코드 짜실 때 추가적으로 리팩토링하면 좋을 것 같습니다!

2024-01-04 01:35 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +	}
현재 이렇게 댓글리스트를 주면 댓글인지 대댓글인지 구분 못하지 않나요??

2024-01-04 01:46 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +	}
![image](https://github.com/ConceptBe/conceptbe-backend/assets/68494227/56591699-98fa-4091-96ca-f44869652096)

2024-01-04 01:46 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/idea/application/IdeaService.java
> +        }
해당 부분은 이해 못했습니다

2024-01-04 01:47 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +			comment.addParentComment(comment);
지우는 것을 깜빡했네요

2024-01-04 01:47 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +	}
구분되어집니다

2024-01-04 01:50 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/idea/application/IdeaService.java
> +        }
해당하는 비즈니스 로직이 idea 엔티티안에 존재하도록 로직을 짜면 됩니다!

2024-01-04 01:54 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/comment/service/CommentService.java
> +	}
댓글과 해당댓글이 붙어있는건 아니고 섞여서 나오는군여 이 부분은 프론트랑 얘기해보면서 맞춰보시져!

2024-01-04 02:37 UTC, parkmuhyeun approved these changes
정말 고생 많으셨습니다!! 👍🏻👍🏻 빠르게 프론트랑 맞추러 가시죵 🙌

+아 그리고 페이징부분도 추가해야 될 것 같읍니다!

2024-01-04 04:42 UTC, merged