feat: Auth Interceptor, resolver 추가
ConceptBe/conceptbe-backend pull request #8
Opened 2024-01-01 05:54 UTC by parkmuhyeun

## 📄 Summary
- #3 
- #5

Resolver를 통해 나오게 되는 결과값은 AuthCredentials이고 안에 id만 존재합니다. resolver단에서 repository에 접근하는게 별로인거 같아서 유저 식별값인 id만 가지도록 했습니다.

로그인을 해야 사용할 수 있는 api는 @Auth 애노테이션, Optional인 경우에는 @OptionalAuth로 사용하시면 될 것 같습니다!

## 🙋🏻 More
>

2024-01-01 14:00 UTC, kpeel5839 requested changes
모밀! 너무 고생하셨어요!

역시 코드 마스터라서 가독성이 굉장히 좋더군요!

간단간단한 것만 남겼습니다!

읽어보시고 답변 남겨주시면 감사할 것 같아요!

2024-01-01 14:00 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/support/BearerTokenExtractor.java
> +        if (!authorization.matches(BEARER_JWT_REGEX)) {
앞에 Baerer 가 붙어야 한다는 규칙 이외에 다른 규칙이 있는 것인가요?

2024-01-01 14:00 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/support/BearerTokenExtractor.java
> +        return authorization.replace(BEARER_TYPE, "").trim();
아주 깔쌈하게 처리해주셨네요 ! ㅎㅎ 역시 모 밀 모 밀

2024-01-01 14:00 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/presentation/dto/AuthCredentials.java
> +public record AuthCredentials(
사랑스러운 dto 네요

2024-01-01 14:00 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/exception/TokenMissingException.java
> +}
토큰이 누락되었습니다는 어떤가요 허호호호

2024-01-01 14:00 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
> +        String accessToken = BearerTokenExtractor.extract(request);
isCorsRequest 는 프리플라이트 request 인건가요?? 또한 hasNotAuthorization 은 로그인하지 않은 회원이 접근했을 떄를 가정한 것인가요?

2024-01-01 14:00 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
> +        if (CorsUtils.isCorsRequest(request) || hasNotAuthorization(request)) {
id 가 존재한다면, 해당 ID 가 실제로 회원가입이 된 ID 인지 확인하는 로직이 필요하지 않을까요?? 이를 Service 에서 해준다면, 중복되는 로직이 많아질 것 같아서요!

2024-01-01 14:00 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/common/auth/Auth.java
> +public @interface Auth {
LoginRequired 와 LoginNonRequired 도 괜찮을 것 같아요! 모밀 생각은 어떠세요 ??

2024-01-02 01:20 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/auth/support/BearerTokenExtractor.java
> +        if (!authorization.matches(BEARER_JWT_REGEX)) {
Base64 인코딩된 문자열인지 확인하는 정규식입니다!

2024-01-02 01:25 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
> +        String accessToken = BearerTokenExtractor.extract(request);
> isCorsRequest 는 프리플라이트 request 인건가요??

어 실수입니다! ㅋㅋㅋㅋㅋㅋ isCorsRequest가 아니고 isPreFlightRequest로 수정했습니다.

>hasNotAuthorization 은 로그인하지 않은 회원이 접근했을 떄를 가정한 것인가요?

넵 Authorization가 없을 때 프론트에서 별도의 추가처리 안해줘도되도록 처리해놨습니다.

요 부분은 pr에 써놨었어야 좋았겠네여 👍🏻

2024-01-02 01:30 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
> +        if (CorsUtils.isCorsRequest(request) || hasNotAuthorization(request)) {
presentation 이상 단인 interceptor, resolver단에서 repository에 접근하는게 별로인거 같아서 사용 안 했습니다!

해당 부분은 repostiory에 메서드를 잘 뺴놓아서 중복되는 것이 memberRepository.getById() 이 한 줄 밖에 안되어서 요렇게 하는게 더 깔끔하다고 생각했습니닷

매뜌는 어떻게 생각하시나여

2024-01-02 01:32 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/common/auth/Auth.java
> +public @interface Auth {
고것도 좋은거 같읍니다.

근데 Auth라는 말이 왠지 간지가 나지 않나여? ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-01-02 01:56 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/common/auth/Auth.java
> +public @interface Auth {
간지나긴하죠! 엉덩이! 그대로갑시다

2024-01-02 01:57 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
> +        if (CorsUtils.isCorsRequest(request) || hasNotAuthorization(request)) {
아하! 짜피 id 로 멤버 조회할 때 없다면 exception 이 터지겠군요! 이 부분을 리뷰하면서 생각하지 못했네요 역시 최고얌

2024-01-02 03:50 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
> +        if (CorsUtils.isCorsRequest(request) || hasNotAuthorization(request)) {
음... 길을 거닐며 조금 더 생각을 해봤는데, 중복코드가 무조건 안 좋은 것은 아니지만, 해당 문제는 ArgumentResolver 에서 Member 를 조회해서 넘겨주면 쉽게 해결해줄 수 있는 문제라서, 조금 고민이 되긴 하네요.. 물론 모밀모밀짱(사랑해)이 말씀하신 것처럼, 한줄이긴 하지만요! 혹시 ArgumentResolver 에서 Repository 를 통해 조회를 시작하게 되면, 커넥션을 너무 오래잡고 있어서 이러한 걱정을 하고 계신 걸까요?? 그렇다면 OSIV 설정을 false 로 두어 트랜잭션이 끝났을 때, 바로 커넥션을 반환하게 하면 어떨까요?? 만일 이 상황에서 지연로딩으로 인한 예외가 발생하게 되면 그 떄 해결해도 늦지 않지 않을까요?

2024-01-02 04:08 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
> +        if (CorsUtils.isCorsRequest(request) || hasNotAuthorization(request)) {
false로 하게되면 준영속상태로 반환되게 되어 추후에 문제가 생길 수도 있을 것 같아용

이거 한번 읽어보면 좋을 것 같습니다!!
[https://kth990303.tistory.com/427](https://kth990303.tistory.com/427)

2024-01-02 04:41 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
> +        if (CorsUtils.isCorsRequest(request) || hasNotAuthorization(request)) {
네네! 준영속 상태로 반환하게 되어서, 업데이트 할 때 문제가 생길 수 있다는 점 인지했습니다. 그리고 제가 말씀드렸던 지연로딩으로 인한 문제도 발생할 수 있겠죠!

하지만, ArgumentResolver 로 들어온 Member 객체를 수정할 일이 있을까라는 생각과, 실제로 수정하게 된다면, 한번 더 조회하면 되지 않을까요 ??

Member 를 수정하는 일은 적은 반면, Member 를 사용하는 일이 많으니, 중복코드를 줄이는 이점이 조금 더 크게 작용할 수도 있을 것 같아서요!

2024-01-02 04:42 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
> +        if (CorsUtils.isCorsRequest(request) || hasNotAuthorization(request)) {
하지만 댓글을 적으며 생각해보니, OneToMany 에 컬럼에 추가하는 경우도 문제가 될 수 있겠군요

차라리 모밀이 말한 것처럼 ArgumentResolver 에서 Entity 를 반환하지 않고, 이런 사이드 이펙트를 완전히 막는 것이 좋을까요 흠흠.. 곰힌이 되네요

2024-01-02 04:52 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
> +        if (CorsUtils.isCorsRequest(request) || hasNotAuthorization(request)) {
> OneToMany 에 컬럼에 추가하는 경우도 문제가 될 수 있겠군요

맞아여 현재 양방향이 더더욱 많기 때문에 변경감지를 사용하는 경우가 많을 것 같아 Entity를 반환하는 것이 더 위험할 거 같습니닷

2024-01-02 04:55 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
> +        if (CorsUtils.isCorsRequest(request) || hasNotAuthorization(request)) {
그리고 중복이란건 추후에 변경될 가능성이 많을 때 유지보수가 어려워진다는 것인데 geyById() 메서드가 변경될 가능성은 거의 없어 보여용

2024-01-02 05:02 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/auth/presentation/AuthInterceptor.java
> +        if (CorsUtils.isCorsRequest(request) || hasNotAuthorization(request)) {
> 그리고 중복이란건 추후에 변경될 가능성이 많을 때 유지보수가 어려워진다는 것인데 geyById() 메서드가 변경될 가능성은 거의 없어 보여용

이렇게 볼 수도 있고, 실제로 코드를 작성할 때 들이는 폼의 차이도 있을 것 같은데, 차이가 크지 않은 것 같아요!

이대로 가! 시! 져!

2024-01-02 05:26 UTC, dnd2dnd reviewed
수고하셨습니다.

2024-01-02 06:21 UTC, kpeel5839 approved these changes
변경사항 확인했습니다! 모밀 고생하셨어요~!

2024-01-03 00:27 UTC, merged