feat: 회원가입 할 때 스킬, 목적 관련 로직 추가 및 스킬 조회 api 추가
ConceptBe/conceptbe-backend pull request #9
Opened 2024-01-04 08:54 UTC by parkmuhyeun

## 📄 Summary
- #3 

몇개 추가 안한거 같은데 코드가 500줄이네요..? 그래도 복잡한 로직은 없고 단순한 것들이라 금방 읽으실 것 같습니다.

해당 PR에서 한 것들은
- 회원가입 할 때 스킬, 목적 관련 로직 추가
- 최소한의 필요한 부분 테스트 코드 작성
- 대분류, 상세분류 스킬 조회 api 추가

## 🙋🏻 More
>  억 ㅋㅋㅋㅋㅋ feat/#3에서 작업해야되는데 feat/#2쪽에서 해버렸네요? 그래도 뒤에 - 붙여놔서 상관없을 것 같습니다

2024-01-05 00:27 UTC, dnd2dnd reviewed
수고하셨습니다.

2024-01-05 00:27 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/member/application/dto/SignUpRequest.java
> +            Region.from(livingPlace)
livingPlace 자료형을 Enum이 아닌 String으로 했을 때 어떤 이점이 있나요?

2024-01-05 00:27 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/member/exception/NotFoundMemberException.java
> +    }
member 외에 주 키가 없는 것들에 대해서 IllegalArgumentException가 아닌 해당하는 CustomException을 만드실건가요??

2024-01-05 00:27 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
메소드 길이가 길어지는 것들에 대해서는 jpql을 사용하실건가요?

2024-01-05 00:47 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/member/application/dto/SignUpRequest.java
> +            Region.from(livingPlace)
String보단 Enum의 장점이 훨씬 많아 Enum으로 했습니다. 가장 큰 장점으로는 하나의 enum 객체로 validate나 어떤 값이 있는지 한 눈에 알 수 있다는 장점이 있습니다!

2024-01-05 00:49 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/member/exception/NotFoundMemberException.java
> +    }
넵 얘기해봐야겠지만 저는 주로 이렇게 사용합니다!

2024-01-05 00:51 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
쿼리메서드로 해결할 수 있는건 쿼리메소드로 해결하고 복잡한 동적 쿼리같은 경우는 querydsl을 도입해볼 수 있을 것 같습니다. 간단한 건 jpql로 해결해도 충분할 것 같아요.

2024-01-05 01:16 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/member/application/dto/SignUpRequest.java
> +            Region.from(livingPlace)
반대로 보신 것 같은데 SignUpRequest의 livingPlace의 자료형을 String으로 쓰셨는데 Enum으로 받으면 안되나요?

2024-01-05 01:28 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
해당 메소드도 쿼리메소드로 해결할 수 있을 것 같은데 jpql 사용하신 이유가 궁금했습니다.

사용해야한다면 jpql은 comple 환경에서 오류를 잡지 못하니 querydsl을 사용하는 것이 어떤가요 ??

2024-01-05 01:36 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/member/application/dto/SignUpRequest.java
> +            Region.from(livingPlace)
Request에서 enum을 받을려면 @JsonCreator나 Converter를 추가해줘야되기 때문에 이렇게 했습니다.

2024-01-05 01:46 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
querydsl을 쓰면 물론 그런 장점 + 장기적으로 좋을 수 있겠지만 학습곡선으로 인해 현재 팀원이 다 알아야 되고 추후에 새로 들어오는 팀원까지 querydsl을 학습해야 됩니다. 그리고 현재 빠르게 MVP를 구현해야 되는 상황에서 추가적인 의존성으로 인한 복잡성으로 시간이 지체되는 걸 고려했을 때 지금같은 방식이 더 적당하다고 판단했습니다.

저도 원래라면 선웅님 말처럼 querydsl을 도입 했을거 같은데 현재 저희 상황을 봤을 때 기한은 촉박하나 현재 해당 기술 도입으로 인한 이득이  거의 없기 때문에 추후에 도입하는 것이 더 좋을 것 같아요!

선웅님은 어떠신가요!?

2024-01-05 01:48 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
아 그리고 추가적으로 위의 쿼리는 equal and notEqual인데 쿼리메서드로 테스트 했을 때 오류가 발생했어서 해당 방법처럼 했는데 혹시 가능하다면 알려주시면 감사하겠습니다!!

2024-01-05 05:28 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/member/application/dto/SignUpRequest.java
> +            Region.from(livingPlace)
네 감사합니다

2024-01-05 05:32 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
![image](https://github.com/ConceptBe/conceptbe-backend/assets/68494227/d7394f52-2615-4ba3-8643-8a89e4af7155)

findByIdNotAndParentSkillCategory_Id 이렇게 사용했습니다.

jpql 사용이유가 해당 메소드 생긴거랑 매개변수 같은거 2번 받는게 마음에 안드신 줄 알았습니다.

2024-01-05 05:49 UTC, dnd2dnd commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
![image](https://github.com/ConceptBe/conceptbe-backend/assets/68494227/711c97f8-ec57-4b43-a8fc-c853f234f63a)

처음에는 이런 메소드를 생각했습니다.
아마도 저는 자기참조 테이블을 생성할 시 parent를 보통 null로 두기 때문인 것 같습니다.

<br>

---

<br>

제 개인적인 의견으로는 위에 enum 질문도 마찬가지이지만, 사실 저는 어떤 것이든 사용해도 상관없습니다.
그냥 사용 이유나 어떻게 생각하시나해서 물어봤습니다....


프로젝트 측면에서 보면 ...
저는 제 파트밖에 잘 모르지만 join이 별로 없는 것 같고, 대부분 일대다로 연관관계를 맺어놔서 entity들을 가져올 수 있으니 안써도 될 것 같긴합니다.

여담으로
" 학습곡선으로 인해 현재 팀원이 다 알아야 되고 추후에 새로 들어오는 팀원까지 querydsl을 학습해야 됩니다."
이런 말씀을 하셔서 이야기를 하자면, 만약 제가 새로운 팀원이고 컨셉비라는 팀에서 제가 모르는 기술이나 코드를 짜는 방식을 쓰고 있다면 저는 좋아서.. 허허

2024-01-05 06:03 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
저도 완전 오픈마인드라 선웅님이랑 비슷하게 사실 어느 것을 사용해도 좋긴합니당! 어떤 것을 선택하더라도 각 측면에서 여러가지 장점이 있기 때문인데여

근데 제가 이번 프로젝트에서 목표하는게 있다면 기술적인 측면보다 좀 더 운영적인 측면이나 실서비스 측면에서 많은 걸 경험해 보고 싶어서입니닷! 저희가 사실 프로젝트에 어떤 기술을 적용하는 건 어렵지 않다고 생각합니다. 하지만, 실제 현업에서는 어떻게 판단해서 하고 실제 장기간동안 운영하다 발생하는 오류를 어떻게 대처하는지에 대해서는 경험해보기 어렵다고 생각해서 이번에 그쪽으로 좀 더 중점으로 생각해서 하면 좋을 것 같아서 작성해봤습니다!

저희가 현재 초반 온보딩하는 과정 중이라 서로 코드 스타일이나 방식같은게 다른 건 당연하다고 생각합니다! 그래서 언제든지 자유롭게 코드에 대해 의견을 남겨주셔도 좋고 왜 이렇게 짯는지 질문을 남겨주셔도 좋습니다! 저도 답변할 때 많은 것을 배우기 때문에 기분 좋게 답변하는거라 언제든지 편하게 남겨주시면 될 것 같습니다. 🙇🏻‍♂️

2024-01-05 06:05 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
> findByIdNotAndParentSkillCategory_Id 이렇게 사용했습니다.

여기서 통일성 맞춰서 findByIdNotAndParentSkillCategoryId으로 가겠습니닷!!

2024-01-05 06:09 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
>저희가 현재 초반 온보딩하는 과정 중이라 서로 코드 스타일이나 방식같은게 다른 건 당연하다고 생각합니다! 그래서 언제든지 자유롭게 코드에 대해 의견을 남겨주셔도 좋고 왜 이렇게 짯는지 질문을 남겨주셔도 좋습니다! 저도 답변할 때 많은 것을 배우기 때문에 기분 좋게 답변하는거라 언제든지 편하게 남겨주시면 될 것 같습니다. 

그리고 코드 구현하실 때도 의논하고 싶으신거 있으셔두 언제든지 dm 하셔두 됩니다! 오히려 좋아!

2024-01-06 17:09 UTC, kpeel5839 requested changes
모밀! 제가 감기가 너무 심하게 걸려가지고 리뷰가 늦었습니다... 죄송해요

간단하게 코멘트 몇개 남겨봤어요!

사랑해연

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/common/entity/domain/persistence/PurposeRepository.java
> +    default Purpose getById(Long id) {
항상 말씀하시던 getById 가 이것이었군요!

default method 로 극으로 활용하는 것 같아서 엄청 좋은 것 같아요

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/Region.java
> +
요구사항 분석까지 완벽하군요 역시 모밀짱 엉덩이

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/purpose/exception/NotFoundPurposeException.java
> +    public NotFoundPurposeException(Long purposeId) {
사랑스러워

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/exception/NotFoundOauthMemberException.java
> +        super(new ErrorCode(BAD_REQUEST, format("Oauth 아이디가 %s인 멤버를 찾을 수 없습니다.", oauthId)));
앞선 Oauth 서버는 a 가 소문자이고, 뒤에는 대문자에요 신경써주세요 내사랑 ^.^

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/exception/NotFoundOauthMemberException.java
> +        super(new ErrorCode(BAD_REQUEST, format("Oauth 아이디가 %s인 멤버를 찾을 수 없습니다.", oauthId)));
그리고 ConceptBeException 을 상속받은 Exception 은 사용자에게 보여지는 Exception 이라고 저는 이해하고 있어요! 그렇기 때문에 Oauth 서버라는 단어보다 플랫폼이라는 단어를 활용하여, 사용자에게 친숙한 단어를 사용하는 것은 또 어떨까요? 근데, 생각해보니 이 Exception 이 터지려면 사용자가 따로 Http 요청을 구성해서 보내야겠군요, 일반적인 사용자는 아닐 것 같네요 허 허 허

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
추후 분류가 더 추가가 된다면, 각 Depth 의 스킬들을 묶어서 한번에 반환하는 게 나을 것 같아요! 모밀은 어떻게 생각하세요?

ex ) 첫번째 분류 - {..}, 두번째 분류 - {..} ... 이런 식으로요!

그렇게 하면 Skill 들을 전부다 가져와서 분류하는 추가적인 비즈니스 로직도 필요할 것 같네요, 근데 Skill 은 원래 Table 에 저장되어 있는 값이니까 다 조회하더라도 부하가 크지 않을 것 같아요.

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/MemberRepository.java
>  }
default 메서드 진짜 잘 활용하시네요 굳

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +        Member member = signUpRequest.toMember();
모밀은 DTO -> Entity 도 굉장히 잘 사용하시네요, 저도 활용해보겠습니다. 또 한 수 배워갑니다!

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +    }
```java
memberSkills.forEach(member::addSkill);
```

다음과 같이 foreach 를 사용하지 않으신 이유가 있나요?

옛날에 주드가 forEach 는 이럴 때 쓰는거다.. 이런 게시글을 올렸던 적이 있었던 것 같은데 정확히 읽지 못해서 호호호, 만일 이유가 있으시다면 알려주실 수 있을까요??

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +            .map((skillRequest) -> {
() 는 붙이지 않아도 괜찮을 것 같아요!

근데, `mapToMemberPurpose` 도 보니까 () 를 붙이는 걸 좋아하시는군용

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +            }).toList();
저는 이런 부분이 있을시에는 가독성을 위해 메서드로 빼는 것을 선호하는데요! 모밀은 어떠신가요?

그리고 검증 최고입니당 ㅎㅎ

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +            }).toList();
그리고, 제안 하나 드리자면, findByIdIn 으로 한번에 찾고, 검색 결과의 Size 와 signUpRequest 에 들어있는 skills 사이즈와 비교해서 유효성을 검증하는 방법은 어떨까요?? 물론 쿼리 횟수를 줄이는 것은 나중 일이긴 하지만요 홍홍홍, 일단 빠르게 진행하는 것도 좋을 거 같습니다.

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +            }).toList();
근데, 제가 짠 게시글 작성은 이 유효성 검증이 없네요.. 위 방법은 실수하기 좋은 것 같긴합니다.

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +    private void processPurpose(SignUpRequest signUpRequest, Member member) {
가입 목적은 필수인데, 해당 로직대로 처리되게 되면, 목적이 없는 경우도 존재할 것 같아요. 제가 생각하는 게 맞을까요? 내사랑 모밀?

2024-01-06 17:09 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +    private void processPurpose(SignUpRequest signUpRequest, Member member) {
스킬도 의견 동일합니당

2024-01-07 05:57 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/member/exception/NotFoundOauthMemberException.java
> +        super(new ErrorCode(BAD_REQUEST, format("Oauth 아이디가 %s인 멤버를 찾을 수 없습니다.", oauthId)));
마자여 서버측 코드의 실수 아니고서는 이 에러를 만날 수는 없을 거에영

2024-01-07 06:10 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
> 추후 분류가 더 추가가 된다면, 각 Depth 의 스킬들을 묶어서 한번에 반환하는 게 나을 것 같아요!

예를들어 4차까지 분류가 있다고 가정하면, 1차 대분류 스킬을 고르면 2, 3차에서는 어떤 걸 고르는지에 관련 없이 2, 3, 4 모든 스킬이 다 나온다는 뜻인가여?

만약 위에서 말하는게 맞다면 코드 복잡도가 올라갈거 같긴하네여. 만약 추후에 많이 추가되어서 api가 많이 발생해야 한다면 사실 프론트쪽에서 가지고 있는다거나 캐싱을 고려할 수도 있기 때문에 지금은 간단하게 가도 상관없다고 생각합니당.

2024-01-07 06:15 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +    }
Stream은 함수형 프로그래밍에 기초한 패러다임으로 스트림 파이프라인 프로그래밍의 핵심은 부작용 없는 함수 객체라고 생각합니다. 그래서 forEach로 외부의 상태를 오염시킬 수 있는 연산 자체는 지양하고 있습니다!

2024-01-07 06:18 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +            .map((skillRequest) -> {
ㅋㅋㅋㅋ 빠르게 구현을 위해 사실 이런부분은 별로 상관 안 썼읍니다.

2024-01-07 06:20 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +    private void processPurpose(SignUpRequest signUpRequest, Member member) {
아 validation 부분은 이 pr이 머지되면 그 다음에 올리려고 대기중입니닷!

2024-01-07 06:25 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +            }).toList();
> 저는 이런 부분이 있을시에는 가독성을 위해 메서드로 빼는 것을 선호하는데요! 모밀은 어떠신가요?

mapToMemberSkills로 뺏다고 생각하는데 혹시 아랫 부분 말씀하시는 걸까영?

```java
skillRequest -> {
                SkillCategory skill = skillCategoryRepository.getById(skillRequest.skillId());
                return new MemberSkillCategory(member, skill, SkillLevel.from(skillRequest.level()));
            }
```

> 그리고, 제안 하나 드리자면, findByIdIn 으로 한번에 찾고, 검색 결과의 Size 와 signUpRequest 에 들어있는 skills 사이즈와 비교해서 유효성을 검증하는 방법은 어떨까요?? 물론 쿼리 횟수를 줄이는 것은 나중 일이긴 하지만요 홍홍홍, 일단 빠르게 진행하는 것도 좋을 거 같습니다.

좋은 것 같습니당. 추후 리팩터링 할 때 고치겠씁니다!

2024-01-07 06:37 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/exception/NotFoundOauthMemberException.java
> +        super(new ErrorCode(BAD_REQUEST, format("Oauth 아이디가 %s인 멤버를 찾을 수 없습니다.", oauthId)));
메세지요 내사랑

2024-01-07 06:38 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +            }).toList();
skillRequest 가지고 MemberSkillCategory 반환하는거 말씀드렸습니당!

2024-01-07 06:39 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +    private void processPurpose(SignUpRequest signUpRequest, Member member) {
알러뷰

2024-01-07 06:41 UTC, kpeel5839 commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
맞아요 지금은 간단하게 가도 괜찮을 것 같아요!

근데, 이제 분류가 더 추가가 되면 사용자에게 어떤 스킬이 어떤 단계의 분류인지 보여주려면 api 를 나눠서 요청하기 보다는, 요청 한번에 스킬 - 분류의 레벨 로 묶어서 반환하는 것이 어떨까해서 코멘트 달았습니다

2024-01-07 06:44 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/member/application/MemberService.java
> +            }).toList();
말하는대로 하면 코드가 어떻게 되는지 한번 보여주실 수 있나여

2024-01-07 06:48 UTC, parkmuhyeun commented on src/main/java/kr/co/conceptbe/skill/domain/SkillCategoryRepository.java
> +}
좋아영 요 부분도 리팩토링 목록에 추가해놓겠읍니다!

2024-01-07 13:57 UTC, kpeel5839 approved these changes
고생했더연 내사랑 모밀! 머지 가즈아!

2024-01-07 14:20 UTC, merged